apiVersion: apps/v1
kind: Deployment
metadata:
  name: ollama-deployment
  namespace: iiitb-chatbot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ollama
  template:
    metadata:
      labels:
        app: ollama
    spec:
      containers:
        - name: ollama
          image: ollama/ollama
          ports:
            - containerPort: 11434
          lifecycle:
            postStart:
              exec:
                command:
                  - sh
                  - -c
                  - |
                    echo "Waiting for ollama service to start..."
                    until curl -s http://localhost:11434 > /dev/null; do
                      sleep 2
                    done
                    echo "Ollama is up. Pulling models..."
                    for model in nomic-embed-text llama3.2; do
                      if ! ollama list | grep -q "$model"; then
                        echo "Pulling $model..."
                        ollama pull "$model"
                      else
                        echo "$model already exists, skipping."
                      fi
                    done
