- name: Install and setup Minikube on Ubuntu WSL
  hosts: localhost
  become: true

  vars:
    repo_url: "https://github.com/ArchisKulkarni00/SPE-Major-Project.git"
    project_dir: "/tmp/ansible-college-chatbot"
    repo_url_fe: "https://github.com/nitin-rajesh/rag-chatbot.git"
    project_dir_fe: "/tmp/ansible-college-chatbot-fe"
    k8s_manifest_dir: "{{ project_dir }}/k8s"
    k8s_manifest_dir_fe: "{{ project_dir_fe }}/K8s"
    minikube_bin_path: "/usr/local/bin/minikube"

  tasks:
    - name: Ensure apt cache is updated
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Install required dependencies
      apt:
        name:
          - curl
          - apt-transport-https
          - ca-certificates
          - gnupg
          - conntrack
        state: present

    - name: Ensure Docker is installed
      apt:
        name: docker.io
        state: present

    - name: Check if kubectl exists in /usr/local/bin
      stat:
        path: /usr/local/bin/kubectl
      register: kubectl_usr_local

    - name: Check if kubectl exists in /snap/bin
      stat:
        path: /snap/bin/kubectl
      register: kubectl_snap

    - name: Download kubectl only if not found
      get_url:
        url: "https://dl.k8s.io/release/v1.29.0/bin/linux/amd64/kubectl"
        dest: /usr/local/bin/kubectl
        mode: '0755'
      when: not kubectl_usr_local.stat.exists and not kubectl_snap.stat.exists

    - name: Check if Minikube is already installed
      stat:
        path: "{{ minikube_bin_path }}"
      register: minikube_stat

    - name: Download Minikube if not already installed
      get_url:
        url: https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
        dest: "{{ minikube_bin_path }}"
        mode: '0755'
      when: not minikube_stat.stat.exists

    - name: Clone project repo if not already present
      git:
        repo: "{{ repo_url }}"
        dest: "{{ project_dir }}"
        update: yes
    
    - name: Clone front end project repo if not already present
      git:
        repo: "{{ repo_url_fe }}"
        dest: "{{ project_dir_fe }}"
        update: yes
        version: "Archis-config"

    # - name: Set up Minikube for linuxboi
    #   become_user: linuxboi
    #   environment:
    #     HOME: "/home/linuxboi"
    #     MINIKUBE_HOME: "/home/linuxboi"
    #     KUBECONFIG: "/home/linuxboi/.kube/config"
    #     PATH: "/home/linuxboi/bin:/usr/local/bin:{{ ansible_env.PATH }}"
    #   shell: |
    #     mkdir -p $HOME/.kube $HOME/.minikube
    #     touch $HOME/.kube/config
    #     minikube start --driver=docker --force --alsologtostderr
    #   args:
    #     executable: /bin/bash
    
    # - name: Apply Kubernetes manifests using kubectl
    #   become_user: linuxboi
    #   environment:
    #     HOME: "/home/linuxboi"
    #     KUBECONFIG: "/home/linuxboi/.kube/config"
    #     PATH: "/home/linuxboi/bin:/usr/local/bin:{{ ansible_env.PATH }}"
    #   shell: |
    #     kubectl apply -f {{ k8s_manifest_dir }} --recursive
    #   args:
    #     executable: /bin/bash
